### ISSUE TITLE
Not working on PDF files

### ISSUE THREAD

**Issue by atanasna** [gsingh93/regex-search#28]
Hello

When you open a PDF in the default pdf viewer in chrome the extension is not able to find even a single exact match, while the native search(Ctrl-F) does this perfectly.
Could you please add this feature as big part of the information that I and others search resides in files.

Thanks
BR

**Comment by ComFreek** [comment]
It does not work since regex-search operates on DOM and PDF.js* draws onto a canvas.

It might be possible to query PDF.js for the text on a page or to integrate that functionality directly into PDF.js (see [here](https://github.com/mozilla/pdf.js/pull/5579) for a similar pull request).
Hooking regex search onto an external plugin will be much more complicated, if not impossible.

*) the viewing engine Chrome Canary uses at least on my system

**Comment by gsingh93** [comment]
I'm going to close this as being out of the scope of this project. Thanks for the suggestion.
